package themes

import (
	"bytes"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

//go:embed *.json
var defaultFS embed.FS

// PreferredOrder keeps the historical built-in dropdown order.
var PreferredOrder = []string{
	"github-light",
	"solarized-light",
	"catppuccin-latte",
	"catppuccin-mocha",
	"dracula",
	"tokyo-night",
	"one-dark",
	"nord",
}

// Theme is an xterm.js ITheme color map.
type Theme map[string]string

// Catalog loads built-in themes and optional on-disk overrides/additions.
type Catalog struct {
	// Dir is an optional filesystem directory of *.json theme files.
	// Files here override embedded defaults with the same stem name and
	// can introduce additional themes without rebuilding the binary.
	Dir string
}

// Load returns the merged theme map. Embedded defaults always load first;
// files from Dir overlay them when the directory exists.
func (c *Catalog) Load() (map[string]Theme, error) {
	out := make(map[string]Theme)
	if err := loadFS(defaultFS, ".", out); err != nil {
		return nil, fmt.Errorf("load embedded themes: %w", err)
	}
	dir := strings.TrimSpace(c.Dir)
	if dir == "" {
		return out, nil
	}
	info, err := os.Stat(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return out, nil
		}
		return nil, fmt.Errorf("stat themes dir %q: %w", dir, err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("themes dir %q is not a directory", dir)
	}
	if err := loadDir(dir, out); err != nil {
		return nil, err
	}
	return out, nil
}

// Names returns theme ids in a stable UI-friendly order.
func (c *Catalog) Names() ([]string, error) {
	all, err := c.Load()
	if err != nil {
		return nil, err
	}
	return orderedNames(all), nil
}

// WriteJS writes a window.GOWEBSSH_THEMES assignment for the frontend.
func (c *Catalog) WriteJS(w io.Writer) error {
	all, err := c.Load()
	if err != nil {
		return err
	}
	payload, err := json.Marshal(all)
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(w, "/* generated by go-webssh */\nwindow.GOWEBSSH_THEMES = %s;\n", payload)
	return err
}

func orderedNames(all map[string]Theme) []string {
	seen := make(map[string]bool, len(all))
	names := make([]string, 0, len(all))
	for _, name := range PreferredOrder {
		if _, ok := all[name]; ok {
			names = append(names, name)
			seen[name] = true
		}
	}
	extra := make([]string, 0)
	for name := range all {
		if !seen[name] {
			extra = append(extra, name)
		}
	}
	sort.Strings(extra)
	return append(names, extra...)
}

func loadDir(dir string, out map[string]Theme) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read themes dir %q: %w", dir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(strings.ToLower(name), ".json") {
			continue
		}
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read theme %q: %w", path, err)
		}
		id := strings.TrimSuffix(name, filepath.Ext(name))
		theme, err := parseTheme(id, data)
		if err != nil {
			return fmt.Errorf("theme %q: %w", path, err)
		}
		out[id] = theme
	}
	return nil
}

func loadFS(fsys fs.FS, root string, out map[string]Theme) error {
	return fs.WalkDir(fsys, root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(strings.ToLower(d.Name()), ".json") {
			return nil
		}
		data, err := fs.ReadFile(fsys, path)
		if err != nil {
			return err
		}
		id := strings.TrimSuffix(d.Name(), filepath.Ext(d.Name()))
		theme, err := parseTheme(id, data)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		out[id] = theme
		return nil
	})
}

func parseTheme(defaultID string, data []byte) (Theme, error) {
	data = bytes.TrimSpace(data)
	if len(data) == 0 {
		return nil, fmt.Errorf("empty theme file")
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("invalid json: %w", err)
	}
	theme := Theme{}
	for key, value := range raw {
		if key == "name" {
			// Optional display metadata; theme id always comes from the filename.
			continue
		}
		s, ok := value.(string)
		if !ok {
			return nil, fmt.Errorf("color %q must be a string", key)
		}
		s = strings.TrimSpace(s)
		if s == "" {
			return nil, fmt.Errorf("color %q is empty", key)
		}
		theme[key] = s
	}
	if theme["background"] == "" || theme["foreground"] == "" {
		return nil, fmt.Errorf("background and foreground are required")
	}
	if defaultID == "" {
		return nil, fmt.Errorf("theme id is required")
	}
	return theme, nil
}
